services:
    ecv_php:
        image: appus/php-dev:8.3.7
        #build:
        #    context: ./container/php
        #    args:
        #        PHP_VERSION: ${PHP_VERSION}
        #        APCU_VERSION: ${APCU_VERSION}
        #        COMPOSER_VERSION: ${COMPOSER_VERSION}
        #        COMPOSER_ALLOW_SUPERUSER: ${COMPOSER_ALLOW_SUPERUSER}
        #        COMPOSER_NO_INTERACTION: ${COMPOSER_NO_INTERACTION}
        container_name: ecv_php
        volumes:
        - ${APP_ECV_DIR}:/var/www/ecv:cached
        - ./home/ecv_php:/root:delegated
        links:
        - ecv_mysql
        - ecv_postgres
        - ecv_mailcatcher
        working_dir: /var/www/ecv
        # HTTP (Serveur SF)
        ports:
            - target: 8000
              published: ${SF_SERVER_PORT:-8000}
              protocol: tcp

    ecv_mysql:
        image: mariadb:${MARIADB_VERSION}
        container_name: ecv_mysql
        volumes:
        - ecv_mysql:/var/lib/mysql:delegated
        # ports:
        #     - target: 3306
        #       published: ${MYSQL_PORT:-3306}
        #       protocol: tcp
        env_file:
        - ./mysql_ecv.env

    ecv_postgres:
        image: postgres:${POSTGRES_VERSION}
        container_name: ecv_postgres
        volumes:
            - ecv_postgres:/var/lib/postgresql/data:delegated
        # ports:
        #     - target: 5432
        #       published: ${POSTGRES_PORT:-5432}
        #       protocol: tcp
        env_file:
            - ./postgres_ecv.env

    ecv_node:
        build:
            context: ./container/node-webpack
            args:
                NODE_VERSION: ${NODE_VERSION}
        container_name: ecv_node
        volumes:
        - ${APP_ECV_DIR}:/var/www/ecv:cached
        - ./home/ecv_node:/home/dev:delegated
        working_dir: /var/www/ecv

    ecv_nginx:
        build:
            context: ./container/nginx
            args:
                NGINX_VERSION: ${NGINX_VERSION}
                SERVER_NAME: ${SERVER_NAME:-localhost}
        container_name: ecv_nginx
        volumes:
        - ${APP_ECV_DIR}:/var/www/ecv:cached
        - ./var/log/nginx:/var/log/nginx:delegated
        links:
        - ecv_php

        ports:
            # HTTP http://localhost (ou autre si màj nginx/ecv.conf:3
            - target: 80
              published: ${NGINX_NDD_PORT:-80}
              protocol: tcp
            # HTTP http://localhost
            - target: 8080
              published: ${NGINX_LOCALHOST_PORT:-8081}
              protocol: tcp

    ecv_caddy:
        image: caddy:${CADDY_VERSION}-alpine
        container_name: ecv_caddy
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
        volumes:
            - ./container/caddy/Caddyfile:/etc/caddy/Caddyfile
            - ${APP_ECV_DIR}:/var/www/ecv:cached
            - ./var/log/caddy:/var/log:delegated
            - ecv_caddy_data:/data
            - ecv_caddy_config:/config
        working_dir: /var/www/ecv
        ports:
            # HTTPS
            - target: 443
              published: ${HTTPS_PORT:-443}
              protocol: tcp
            # HTTP/3
            - target: 443
              published: ${HTTP3_PORT:-443}
              protocol: udp
        links:
        - ecv_php

    # #########
    # Dev
    # #########
    ecv_phpmyadmin:
        image: phpmyadmin:${PHPMYADMIN_VERSION}
        container_name: ecv_phpmyadmin
        # HTTP
        ports:
            - target: 80
              published: ${PHPMYADMIN_PORT:-8036}
              protocol: tcp
        links:
        - ecv_mysql
        env_file:
        - ./phpmyadmin.env

    ecv_adminer:
        image: adminer:${ADMINER_VERSION}
        container_name: ecv_adminer
        # HTTP
        ports:
            - target: 8080
              published: ${ADMINER_PORT:-8037}
              protocol: tcp
        links:
        - ecv_mysql
        - ecv_postgres

    ecv_pgadmin:
        image: dpage/pgadmin4:${PGADMIN_VERSION}
        container_name: ecv_pgadmin
        volumes:
            - ecv_pgadmin:/var/lib/pgadmin
        ports:
            # HTTP
            - target: 80
              published: ${PGADMIN_PORT:-8038}
              protocol: tcp
        links:
        - ecv_postgres
        env_file:
        - ./pgadmin_ecv.env

    ecv_mailcatcher:
        image: appus/mailcatcher:0.8.2
        container_name: ecv_mailcatcher
        ports:
        # SMTP
        - target: 1025
          published: ${MAILCATCHER_PORT:-1025}
          protocol: tcp
        # HTTP
        - target: 1080
          published: ${MAILCATCHER_PORT:-1080}
          protocol: tcp

volumes:
    ecv_mysql:
    ecv_postgres:
    ecv_caddy_data:
    ecv_caddy_config:
    ecv_pgadmin: